name: Lint Kotlin and Android Code

on:
  pull_request:
    branches:
      - main # Adjust the branch name as needed

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11' # Adjust the Java version as needed

      - name: Install Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-version: '30' # Adjust the Android SDK version as needed

      - name: Run ktlint
        run: |
          ./gradlew ktlintCheck
        working-directory: your/android/project/directory # Adjust the path

      - name: Run lint
        run: |
          ./gradlew lint
        working-directory: your/android/project/d
